### PR TITLE
Add support for array of simple types

### PR DESCRIPTION
**Pull request by maks-baum**

### CODE REVIEW

**Comment by camcima** [comment]
Thanks! There's one thing I did not understand. Why is the property name hardcoded as `item`? Is this a WSDL standard or is it just the case for this specific webservice?

**Comment by maks-baum** [comment]
It's always item - doesn't matter if there is one item or more, name of attribute is always item.
If you don't use features => SOAP_SINGLE_ELEMENT_ARRAYS you can have in this attribute one element (i did additional conditional statement to avoid this situation and create array with one element in it)

forecasticons

**Comment by camcima** [comment]
After looking at the WSDL for the test, I could see the the `item` variable in this case, is just a name chosen for this particular webservice:

```
<xsd:sequence>
<xsd:element name="item" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType>
```

I suggest we implemented like this:

```php
        // If object is array of simple types just return inner array stored in item attribute
        if (is_object($obj) && array_key_exists($className, $classMap) && $classMap[$className] === 'array') {

            return json_decode(json_encode($obj), true);
        } elseif (is_object($obj)) {
```

In this case, it will convert the whole object to an array, and not only the `item`property.In your test, the output would be something like this:

```
array(1) {
  ["item"]=>
  array(3) {
    [0]=>
    string(18) "partly-cloudly.png"
    [1]=>
    string(14) "light-rain.png"
    [2]=>
    string(18) "mostly-cloudly.png"
  }
}
```

**Comment by maks-baum** [comment]
hm.. this wsdl is autogenerated with zend, cannot change `item` name.
```php
    /**
     * @return string[]
     */
    public function getForecastIcons()
    {
        return ['partly-cloudly.png', 'light-rain.png', 'mostly-cloudly.png'];
    }
```

**Comment by maks-baum** [comment]
I just lokked at some wsdl at work - java sends me records also in this attribute - it was array of objects, but still (and if that wouldn't be default behaviour I'm pretty sure that authors of this java based client would complain on this ;)

**Comment by camcima** [comment]
I've found an example that is different: https://msdn.microsoft.com/en-us/library/dn743170.aspx?f=255&MSPPError=-2147217396

I guess, each implementation can choose its own preferred name. I suggest them that we get the first (and possibly only) property and return that in the array. In that way, we wouldn't need to hardcode `item` and it could support not only `item` but any other property name.

```
        // If object is array of simple types just return inner array stored in item attribute
        if (is_object($obj) && array_key_exists($className, $classMap) && $classMap[$className] === 'array') {
            $result = json_decode(json_encode($obj), true);

            return reset($result);
```

**Comment by maks-baum** [comment]
There is only one problem with this - if you don't set
`\SoapClient('http://',[], ['features' => SOAP_SINGLE_ELEMENT_ARRAYS]);`
then if there is one element in `item` then you won't get array but only one element just like:
```php
object(Api\Dictionary)[7]
  public 'Applications' => string 'test' (length=8)
  public 'Carriers' => 
    array (size=3)
      0 => string '12' (length=2)
      1 => string '32' (length=2)
      2 => string '31' (length=2)
```

**Comment by maks-baum** [comment]
sth like
```php
$return = reset($result);
return is_array($return) ? $return : array($return);
```
should work

**Comment by camcima** [comment]
Last change: please change the name of the variables:

`result` to `payload`
`return` to `result`

**Pull request merged**
